services:
  mysql:
    image: mysql:8.0
    container_name: coupon-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coupon_fifo
      MYSQL_USER: coupon
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: coupon-redis
    ports:
      - "6379:6379"

volumes:
  mysql-data:
